// GENERATED BY generate_catalog.cjs
export const biblicalCategorySuggestions = [
  {
    id: "god",
    name: "God",
    slug: "god",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["god","father","almighty"]
  },
  {
    id: "creator",
    name: "Creator",
    slug: "creator",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["maker","create"]
  },
  {
    id: "almighty-god",
    name: "Almighty God",
    slug: "almighty-god",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["strong","mountain","rock"]
  },
  {
    id: "divine-presence",
    name: "Divine Presence",
    slug: "divine-presence",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["light","shine","glory"]
  },
  {
    id: "glory",
    name: "Glory",
    slug: "glory",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["glory","shine","majesty"]
  },
  {
    id: "majesty",
    name: "Majesty",
    slug: "majesty",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["royal","king"]
  },
  {
    id: "sovereignty",
    name: "Sovereignty",
    slug: "sovereignty",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["rule","earth"]
  },
  {
    id: "holiness",
    name: "Holiness",
    slug: "holiness",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["holy","pure"]
  },
  {
    id: "divine-light",
    name: "Divine Light",
    slug: "divine-light",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["light","sun"]
  },
  {
    id: "god-s-presence",
    name: "God's Presence",
    slug: "god-s-presence",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["presence","near"]
  },
  {
    id: "god-s-glory",
    name: "God's Glory",
    slug: "god-s-glory",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["glory","bright"]
  },
  {
    id: "god-s-power",
    name: "God's Power",
    slug: "god-s-power",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["power","strength","lightning"]
  },
  {
    id: "god-s-kingdom",
    name: "God's Kingdom",
    slug: "god-s-kingdom",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["kingdom","rule"]
  },
  {
    id: "throne",
    name: "Throne",
    slug: "throne",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["seat","throne"]
  },
  {
    id: "alpha-omega",
    name: "Alpha & Omega",
    slug: "alpha-omega",
    group: "God & Divine",
    icon: "undefined",
    keywords: ["beginning","end"]
  },
  {
    id: "jesus-christ",
    name: "Jesus Christ",
    slug: "jesus-christ",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["savior","lord"]
  },
  {
    id: "messiah",
    name: "Messiah",
    slug: "messiah",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["chosen","anointed"]
  },
  {
    id: "savior",
    name: "Savior",
    slug: "savior",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["save","rescue"]
  },
  {
    id: "son-of-god",
    name: "Son of God",
    slug: "son-of-god",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["son","jesus"]
  },
  {
    id: "good-shepherd",
    name: "Good Shepherd",
    slug: "good-shepherd",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["sheep","lead","staff"]
  },
  {
    id: "lamb-of-god",
    name: "Lamb of God",
    slug: "lamb-of-god",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["lamb","sheep","sacrifice"]
  },
  {
    id: "crucifixion",
    name: "Crucifixion",
    slug: "crucifixion",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["nails","cross"]
  },
  {
    id: "resurrection",
    name: "Resurrection",
    slug: "resurrection",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["rise","life"]
  },
  {
    id: "empty-tomb",
    name: "Empty Tomb",
    slug: "empty-tomb",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["stone","empty"]
  },
  {
    id: "crown-of-thorns",
    name: "Crown of Thorns",
    slug: "crown-of-thorns",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["thorns","pain"]
  },
  {
    id: "nails",
    name: "Nails",
    slug: "nails",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["cross","nail"]
  },
  {
    id: "calvary",
    name: "Calvary",
    slug: "calvary",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["hill","place"]
  },
  {
    id: "redemption",
    name: "Redemption",
    slug: "redemption",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["redeem","buy"]
  },
  {
    id: "salvation",
    name: "Salvation",
    slug: "salvation",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["save","secure"]
  },
  {
    id: "blood-of-christ",
    name: "Blood of Christ",
    slug: "blood-of-christ",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["blood","wine"]
  },
  {
    id: "resurrection-life",
    name: "Resurrection Life",
    slug: "resurrection-life",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["life","new"]
  },
  {
    id: "the-way",
    name: "The Way",
    slug: "the-way",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["path","road"]
  },
  {
    id: "the-truth",
    name: "The Truth",
    slug: "the-truth",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["truth","real"]
  },
  {
    id: "the-life",
    name: "The Life",
    slug: "the-life",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["life","pulse"]
  },
  {
    id: "living-water",
    name: "Living Water",
    slug: "living-water",
    group: "Jesus Christ",
    icon: "undefined",
    keywords: ["water","drink"]
  },
  {
    id: "holy-spirit",
    name: "Holy Spirit",
    slug: "holy-spirit",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["spirit","ghost"]
  },
  {
    id: "fire-of-the-spirit",
    name: "Fire of the Spirit",
    slug: "fire-of-the-spirit",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["fire","burn"]
  },
  {
    id: "anointing",
    name: "Anointing",
    slug: "anointing",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["oil","pour"]
  },
  {
    id: "spiritual-gifts",
    name: "Spiritual Gifts",
    slug: "spiritual-gifts",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["gifts","talent"]
  },
  {
    id: "power",
    name: "Power",
    slug: "power",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["power","energy"]
  },
  {
    id: "guidance",
    name: "Guidance",
    slug: "guidance",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["guide","lead"]
  },
  {
    id: "comforter",
    name: "Comforter",
    slug: "comforter",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["comfort","hug"]
  },
  {
    id: "inspiration",
    name: "Inspiration",
    slug: "inspiration",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["idea","inspire"]
  },
  {
    id: "spiritual-fruit",
    name: "Spiritual Fruit",
    slug: "spiritual-fruit",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["fruit","grow"]
  },
  {
    id: "presence",
    name: "Presence",
    slug: "presence",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["wind","breath"]
  },
  {
    id: "renewal",
    name: "Renewal",
    slug: "renewal",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["renew","fresh"]
  },
  {
    id: "counselor",
    name: "Counselor",
    slug: "counselor",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["counsel","advise"]
  },
  {
    id: "advocate",
    name: "Advocate",
    slug: "advocate",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["law","defend"]
  },
  {
    id: "seal",
    name: "Seal",
    slug: "seal",
    group: "Holy Spirit",
    icon: "undefined",
    keywords: ["mark","seal"]
  },
  {
    id: "bible",
    name: "Bible",
    slug: "bible",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["book","word"]
  },
  {
    id: "open-bible",
    name: "Open Bible",
    slug: "open-bible",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["read","open"]
  },
  {
    id: "closed-bible",
    name: "Closed Bible",
    slug: "closed-bible",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["closed","study"]
  },
  {
    id: "scripture",
    name: "Scripture",
    slug: "scripture",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["scroll","text"]
  },
  {
    id: "god-s-word",
    name: "God's Word",
    slug: "god-s-word",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["word","speak"]
  },
  {
    id: "scroll",
    name: "Scroll",
    slug: "scroll",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["ancient","parchment"]
  },
  {
    id: "scripture-study",
    name: "Scripture Study",
    slug: "scripture-study",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["study","learn"]
  },
  {
    id: "reading",
    name: "Reading",
    slug: "reading",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["read","glasses"]
  },
  {
    id: "meditation",
    name: "Meditation",
    slug: "meditation",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["think","meditate"]
  },
  {
    id: "teaching",
    name: "Teaching",
    slug: "teaching",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["teach","school"]
  },
  {
    id: "preaching",
    name: "Preaching",
    slug: "preaching",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["preach","speak"]
  },
  {
    id: "gospel",
    name: "Gospel",
    slug: "gospel",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["news","announce"]
  },
  {
    id: "truth",
    name: "Truth",
    slug: "truth",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["fact","right"]
  },
  {
    id: "knowledge",
    name: "Knowledge",
    slug: "knowledge",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["know","books"]
  },
  {
    id: "understanding",
    name: "Understanding",
    slug: "understanding",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["understand","idea"]
  },
  {
    id: "wisdom",
    name: "Wisdom",
    slug: "wisdom",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["wise","smart"]
  },
  {
    id: "revelation",
    name: "Revelation",
    slug: "revelation",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["reveal","see"]
  },
  {
    id: "covenant",
    name: "Covenant",
    slug: "covenant",
    group: "Bible & Scripture",
    icon: "undefined",
    keywords: ["agreement","pact"]
  },
  {
    id: "prayer",
    name: "Prayer",
    slug: "prayer",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["pray","hands"]
  },
  {
    id: "intercession",
    name: "Intercession",
    slug: "intercession",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["intercede","stand"]
  },
  {
    id: "prayer-request",
    name: "Prayer Request",
    slug: "prayer-request",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["request","list"]
  },
  {
    id: "answered-prayer",
    name: "Answered Prayer",
    slug: "answered-prayer",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["answer","yes"]
  },
  {
    id: "morning-prayer",
    name: "Morning Prayer",
    slug: "morning-prayer",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["morning","day"]
  },
  {
    id: "evening-prayer",
    name: "Evening Prayer",
    slug: "evening-prayer",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["night","evening"]
  },
  {
    id: "fasting",
    name: "Fasting",
    slug: "fasting",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["fast","food"]
  },
  {
    id: "devotion",
    name: "Devotion",
    slug: "devotion",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["devote","love"]
  },
  {
    id: "quiet-time",
    name: "Quiet Time",
    slug: "quiet-time",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["quiet","morning"]
  },
  {
    id: "seeking-god",
    name: "Seeking God",
    slug: "seeking-god",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["seek","find"]
  },
  {
    id: "kneeling",
    name: "Kneeling",
    slug: "kneeling",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["kneel","bow"]
  },
  {
    id: "worship-prayer",
    name: "Worship Prayer",
    slug: "worship-prayer",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["sing","pray"]
  },
  {
    id: "family-prayer",
    name: "Family Prayer",
    slug: "family-prayer",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["family","home"]
  },
  {
    id: "prayer-meeting",
    name: "Prayer Meeting",
    slug: "prayer-meeting",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["meet","group"]
  },
  {
    id: "prayer-warrior",
    name: "Prayer Warrior",
    slug: "prayer-warrior",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["warrior","fight"]
  },
  {
    id: "spiritual-discipline",
    name: "Spiritual Discipline",
    slug: "spiritual-discipline",
    group: "Prayer & Devotion",
    icon: "undefined",
    keywords: ["train","discipline"]
  },
  {
    id: "worship",
    name: "Worship",
    slug: "worship",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["raise","hands"]
  },
  {
    id: "praise",
    name: "Praise",
    slug: "praise",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["celebrate","praise"]
  },
  {
    id: "thanksgiving",
    name: "Thanksgiving",
    slug: "thanksgiving",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["thank","give"]
  },
  {
    id: "celebration",
    name: "Celebration",
    slug: "celebration",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["party","celebrate"]
  },
  {
    id: "singing",
    name: "Singing",
    slug: "singing",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["sing","vocal"]
  },
  {
    id: "choir",
    name: "Choir",
    slug: "choir",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["group","sing"]
  },
  {
    id: "worship-music",
    name: "Worship Music",
    slug: "worship-music",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["music","note"]
  },
  {
    id: "instrument",
    name: "Instrument",
    slug: "instrument",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["play","string"]
  },
  {
    id: "piano",
    name: "Piano",
    slug: "piano",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["keys","piano"]
  },
  {
    id: "drum",
    name: "Drum",
    slug: "drum",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["beat","drum"]
  },
  {
    id: "raised-hands",
    name: "Raised Hands",
    slug: "raised-hands",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["up","raise"]
  },
  {
    id: "dancing",
    name: "Dancing",
    slug: "dancing",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["dance","move"]
  },
  {
    id: "joyful-praise",
    name: "Joyful Praise",
    slug: "joyful-praise",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["joy","happy"]
  },
  {
    id: "adoration",
    name: "Adoration",
    slug: "adoration",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["adore","love"]
  },
  {
    id: "exaltation",
    name: "Exaltation",
    slug: "exaltation",
    group: "Worship & Praise",
    icon: "undefined",
    keywords: ["exalt","high"]
  },
  {
    id: "faith",
    name: "Faith",
    slug: "faith",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["believe","anchor"]
  },
  {
    id: "trust",
    name: "Trust",
    slug: "trust",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["trust","rely"]
  },
  {
    id: "belief",
    name: "Belief",
    slug: "belief",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["believe","true"]
  },
  {
    id: "faithfulness",
    name: "Faithfulness",
    slug: "faithfulness",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["loyal","faithful"]
  },
  {
    id: "hope",
    name: "Hope",
    slug: "hope",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["hope","future"]
  },
  {
    id: "courage",
    name: "Courage",
    slug: "courage",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["brave","bold"]
  },
  {
    id: "boldness",
    name: "Boldness",
    slug: "boldness",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["speak","bold"]
  },
  {
    id: "confidence",
    name: "Confidence",
    slug: "confidence",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["sure","confident"]
  },
  {
    id: "patience",
    name: "Patience",
    slug: "patience",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["wait","time"]
  },
  {
    id: "perseverance",
    name: "Perseverance",
    slug: "perseverance",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["endure","last"]
  },
  {
    id: "endurance",
    name: "Endurance",
    slug: "endurance",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["run","race"]
  },
  {
    id: "waiting-on-god",
    name: "Waiting on God",
    slug: "waiting-on-god",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["wait","time"]
  },
  {
    id: "dependence",
    name: "Dependence",
    slug: "dependence",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["depend","rely"]
  },
  {
    id: "commitment",
    name: "Commitment",
    slug: "commitment",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["commit","sign"]
  },
  {
    id: "dedication",
    name: "Dedication",
    slug: "dedication",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["dedicate","award"]
  },
  {
    id: "obedience",
    name: "Obedience",
    slug: "obedience",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["obey","follow"]
  },
  {
    id: "submission",
    name: "Submission",
    slug: "submission",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["submit","yield"]
  },
  {
    id: "humility",
    name: "Humility",
    slug: "humility",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["humble","low"]
  },
  {
    id: "surrender",
    name: "Surrender",
    slug: "surrender",
    group: "Faith & Spiritual Life",
    icon: "undefined",
    keywords: ["give up","yield"]
  },
  {
    id: "love",
    name: "Love",
    slug: "love",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["love","care"]
  },
  {
    id: "god-s-love",
    name: "God's Love",
    slug: "god-s-love",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["agape","divine"]
  },
  {
    id: "grace",
    name: "Grace",
    slug: "grace",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["grace","favor"]
  },
  {
    id: "mercy",
    name: "Mercy",
    slug: "mercy",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["mercy","pity"]
  },
  {
    id: "compassion",
    name: "Compassion",
    slug: "compassion",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["compassion","feel"]
  },
  {
    id: "kindness",
    name: "Kindness",
    slug: "kindness",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["kind","nice"]
  },
  {
    id: "forgiveness",
    name: "Forgiveness",
    slug: "forgiveness",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["forgive","pardon"]
  },
  {
    id: "reconciliation",
    name: "Reconciliation",
    slug: "reconciliation",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["reconcile","join"]
  },
  {
    id: "acceptance",
    name: "Acceptance",
    slug: "acceptance",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["accept","receive"]
  },
  {
    id: "generosity",
    name: "Generosity",
    slug: "generosity",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["generous","give"]
  },
  {
    id: "charity",
    name: "Charity",
    slug: "charity",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["charity","money"]
  },
  {
    id: "service",
    name: "Service",
    slug: "service",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["serve","help"]
  },
  {
    id: "caring",
    name: "Caring",
    slug: "caring",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["care","health"]
  },
  {
    id: "friendship",
    name: "Friendship",
    slug: "friendship",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["friend","pal"]
  },
  {
    id: "fellowship",
    name: "Fellowship",
    slug: "fellowship",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["fellowship","together"]
  },
  {
    id: "unity",
    name: "Unity",
    slug: "unity",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["unite","one"]
  },
  {
    id: "peace",
    name: "Peace",
    slug: "peace",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["peace","calm"]
  },
  {
    id: "harmony",
    name: "Harmony",
    slug: "harmony",
    group: "Love, Grace & Mercy",
    icon: "undefined",
    keywords: ["harmony","tune"]
  },
  {
    id: "healing",
    name: "Healing",
    slug: "healing",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["heal","fix"]
  },
  {
    id: "divine-healing",
    name: "Divine Healing",
    slug: "divine-healing",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["divine","health"]
  },
  {
    id: "restoration",
    name: "Restoration",
    slug: "restoration",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["restore","fix"]
  },
  {
    id: "miracles",
    name: "Miracles",
    slug: "miracles",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["miracle","wonder"]
  },
  {
    id: "recovery",
    name: "Recovery",
    slug: "recovery",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["recover","health"]
  },
  {
    id: "wholeness",
    name: "Wholeness",
    slug: "wholeness",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["whole","complete"]
  },
  {
    id: "strength",
    name: "Strength",
    slug: "strength",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["strong","power"]
  },
  {
    id: "comfort",
    name: "Comfort",
    slug: "comfort",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["comfort","rest"]
  },
  {
    id: "deliverance",
    name: "Deliverance",
    slug: "deliverance",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["deliver","free"]
  },
  {
    id: "breakthrough",
    name: "Breakthrough",
    slug: "breakthrough",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["break","through"]
  },
  {
    id: "freedom",
    name: "Freedom",
    slug: "freedom",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["free","fly"]
  },
  {
    id: "revival",
    name: "Revival",
    slug: "revival",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["revive","wake"]
  },
  {
    id: "healing-prayer",
    name: "Healing Prayer",
    slug: "healing-prayer",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["pray","heal"]
  },
  {
    id: "emotional-healing",
    name: "Emotional Healing",
    slug: "emotional-healing",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["emotion","mind"]
  },
  {
    id: "spiritual-healing",
    name: "Spiritual Healing",
    slug: "spiritual-healing",
    group: "Healing & Miracles",
    icon: "undefined",
    keywords: ["spirit","heal"]
  },
  {
    id: "spiritual-warfare",
    name: "Spiritual Warfare",
    slug: "spiritual-warfare",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["war","fight"]
  },
  {
    id: "armor-of-god",
    name: "Armor of God",
    slug: "armor-of-god",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["armor","protect"]
  },
  {
    id: "shield-of-faith",
    name: "Shield of Faith",
    slug: "shield-of-faith",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["shield","faith"]
  },
  {
    id: "sword-of-the-spirit",
    name: "Sword of the Spirit",
    slug: "sword-of-the-spirit",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["sword","spirit"]
  },
  {
    id: "helmet-of-salvation",
    name: "Helmet of Salvation",
    slug: "helmet-of-salvation",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["helmet","head"]
  },
  {
    id: "breastplate-of-righteousness",
    name: "Breastplate of Righteousness",
    slug: "breastplate-of-righteousness",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["breastplate","chest"]
  },
  {
    id: "belt-of-truth",
    name: "Belt of Truth",
    slug: "belt-of-truth",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["belt","truth"]
  },
  {
    id: "shoes-of-peace",
    name: "Shoes of Peace",
    slug: "shoes-of-peace",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["shoes","feet"]
  },
  {
    id: "spiritual-battle",
    name: "Spiritual Battle",
    slug: "spiritual-battle",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["battle","fight"]
  },
  {
    id: "victory",
    name: "Victory",
    slug: "victory",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["win","triumph"]
  },
  {
    id: "protection",
    name: "Protection",
    slug: "protection",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["protect","safe"]
  },
  {
    id: "refuge",
    name: "Refuge",
    slug: "refuge",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["hide","safe"]
  },
  {
    id: "stronghold",
    name: "Stronghold",
    slug: "stronghold",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["strong","hold"]
  },
  {
    id: "defender",
    name: "Defender",
    slug: "defender",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["defend","guard"]
  },
  {
    id: "warrior",
    name: "Warrior",
    slug: "warrior",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["warrior","fight"]
  },
  {
    id: "overcoming",
    name: "Overcoming",
    slug: "overcoming",
    group: "Spiritual Warfare",
    icon: "undefined",
    keywords: ["overcome","rise"]
  },
  {
    id: "righteousness",
    name: "Righteousness",
    slug: "righteousness",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["right","just"]
  },
  {
    id: "purity",
    name: "Purity",
    slug: "purity",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["pure","clean"]
  },
  {
    id: "integrity",
    name: "Integrity",
    slug: "integrity",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["honest","true"]
  },
  {
    id: "character",
    name: "Character",
    slug: "character",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["moral","character"]
  },
  {
    id: "discipline",
    name: "Discipline",
    slug: "discipline",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["train","habit"]
  },
  {
    id: "goodness",
    name: "Goodness",
    slug: "goodness",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["good","moral"]
  },
  {
    id: "self-control",
    name: "Self-Control",
    slug: "self-control",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["control","stop"]
  },
  {
    id: "gentleness",
    name: "Gentleness",
    slug: "gentleness",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["gentle","soft"]
  },
  {
    id: "servanthood",
    name: "Servanthood",
    slug: "servanthood",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["serve","slave"]
  },
  {
    id: "leadership",
    name: "Leadership",
    slug: "leadership",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["lead","guide"]
  },
  {
    id: "discernment",
    name: "Discernment",
    slug: "discernment",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["discern","see"]
  },
  {
    id: "growth",
    name: "Growth",
    slug: "growth",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["grow","plant"]
  },
  {
    id: "transformation",
    name: "Transformation",
    slug: "transformation",
    group: "Christian Living",
    icon: "undefined",
    keywords: ["change","transform"]
  },
  {
    id: "fruit-of-love",
    name: "Fruit of Love",
    slug: "fruit-of-love",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["love","fruit"]
  },
  {
    id: "fruit-of-joy",
    name: "Fruit of Joy",
    slug: "fruit-of-joy",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["joy","fruit"]
  },
  {
    id: "fruit-of-peace",
    name: "Fruit of Peace",
    slug: "fruit-of-peace",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["peace","fruit"]
  },
  {
    id: "fruit-of-patience",
    name: "Fruit of Patience",
    slug: "fruit-of-patience",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["patience","fruit"]
  },
  {
    id: "fruit-of-kindness",
    name: "Fruit of Kindness",
    slug: "fruit-of-kindness",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["kindness","fruit"]
  },
  {
    id: "fruit-of-goodness",
    name: "Fruit of Goodness",
    slug: "fruit-of-goodness",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["goodness","fruit"]
  },
  {
    id: "fruit-of-faithfulness",
    name: "Fruit of Faithfulness",
    slug: "fruit-of-faithfulness",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["faithfulness","fruit"]
  },
  {
    id: "fruit-of-gentleness",
    name: "Fruit of Gentleness",
    slug: "fruit-of-gentleness",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["gentleness","fruit"]
  },
  {
    id: "fruit-of-self-control",
    name: "Fruit of Self-Control",
    slug: "fruit-of-self-control",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["self-control","fruit"]
  },
  {
    id: "the-vine",
    name: "The Vine",
    slug: "the-vine",
    group: "Fruit of the Spirit",
    icon: "undefined",
    keywords: ["vine","branch"]
  },
  {
    id: "family",
    name: "Family",
    slug: "family",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["family","home"]
  },
  {
    id: "marriage",
    name: "Marriage",
    slug: "marriage",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["marry","wedding"]
  },
  {
    id: "husband",
    name: "Husband",
    slug: "husband",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["husband","man"]
  },
  {
    id: "wife",
    name: "Wife",
    slug: "wife",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["wife","woman"]
  },
  {
    id: "children",
    name: "Children",
    slug: "children",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["child","kid"]
  },
  {
    id: "parenting",
    name: "Parenting",
    slug: "parenting",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["parent","raise"]
  },
  {
    id: "mother",
    name: "Mother",
    slug: "mother",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["mom","mother"]
  },
  {
    id: "father",
    name: "Father",
    slug: "father",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["dad","father"]
  },
  {
    id: "youth",
    name: "Youth",
    slug: "youth",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["teen","youth"]
  },
  {
    id: "young-adults",
    name: "Young Adults",
    slug: "young-adults",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["college","young"]
  },
  {
    id: "brotherhood",
    name: "Brotherhood",
    slug: "brotherhood",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["brother","men"]
  },
  {
    id: "sisterhood",
    name: "Sisterhood",
    slug: "sisterhood",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["sister","women"]
  },
  {
    id: "community",
    name: "Community",
    slug: "community",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["town","people"]
  },
  {
    id: "relationships",
    name: "Relationships",
    slug: "relationships",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["relate","friend"]
  },
  {
    id: "christian-home",
    name: "Christian Home",
    slug: "christian-home",
    group: "Family & Relationships",
    icon: "undefined",
    keywords: ["home","house"]
  },
  {
    id: "church",
    name: "Church",
    slug: "church",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["church","building"]
  },
  {
    id: "ministry",
    name: "Ministry",
    slug: "ministry",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["work","serve"]
  },
  {
    id: "pastor",
    name: "Pastor",
    slug: "pastor",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["pastor","leader"]
  },
  {
    id: "shepherd",
    name: "Shepherd",
    slug: "shepherd",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["sheep","lead"]
  },
  {
    id: "leader",
    name: "Leader",
    slug: "leader",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["lead","guide"]
  },
  {
    id: "deacon",
    name: "Deacon",
    slug: "deacon",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["serve","help"]
  },
  {
    id: "elder",
    name: "Elder",
    slug: "elder",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["wise","old"]
  },
  {
    id: "mission",
    name: "Mission",
    slug: "mission",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["mission","send"]
  },
  {
    id: "evangelism",
    name: "Evangelism",
    slug: "evangelism",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["gospel","share"]
  },
  {
    id: "outreach",
    name: "Outreach",
    slug: "outreach",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["reach","out"]
  },
  {
    id: "discipleship",
    name: "Discipleship",
    slug: "discipleship",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["disciple","follow"]
  },
  {
    id: "small-group",
    name: "Small Group",
    slug: "small-group",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["small","group"]
  },
  {
    id: "bible-study",
    name: "Bible Study",
    slug: "bible-study",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["study","read"]
  },
  {
    id: "sunday-service",
    name: "Sunday Service",
    slug: "sunday-service",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["sunday","church"]
  },
  {
    id: "sermon",
    name: "Sermon",
    slug: "sermon",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["sermon","speak"]
  },
  {
    id: "worship-team",
    name: "Worship Team",
    slug: "worship-team",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["team","music"]
  },
  {
    id: "youth-ministry",
    name: "Youth Ministry",
    slug: "youth-ministry",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["youth","teen"]
  },
  {
    id: "children-s-ministry",
    name: "Children's Ministry",
    slug: "children-s-ministry",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["child","kid"]
  },
  {
    id: "women-s-ministry",
    name: "Women's Ministry",
    slug: "women-s-ministry",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["women","lady"]
  },
  {
    id: "men-s-ministry",
    name: "Men's Ministry",
    slug: "men-s-ministry",
    group: "Church & Ministry",
    icon: "undefined",
    keywords: ["men","man"]
  },
  {
    id: "god-s-promises",
    name: "God's Promises",
    slug: "god-s-promises",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["promise","word"]
  },
  {
    id: "blessings",
    name: "Blessings",
    slug: "blessings",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["bless","give"]
  },
  {
    id: "provision",
    name: "Provision",
    slug: "provision",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["provide","food"]
  },
  {
    id: "abundance",
    name: "Abundance",
    slug: "abundance",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["abundant","plenty"]
  },
  {
    id: "prosperity",
    name: "Prosperity",
    slug: "prosperity",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["prosper","wealth"]
  },
  {
    id: "favor",
    name: "Favor",
    slug: "favor",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["favor","grace"]
  },
  {
    id: "open-doors",
    name: "Open Doors",
    slug: "open-doors",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["door","open"]
  },
  {
    id: "inheritance",
    name: "Inheritance",
    slug: "inheritance",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["inherit","legacy"]
  },
  {
    id: "reward",
    name: "Reward",
    slug: "reward",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["reward","prize"]
  },
  {
    id: "harvest",
    name: "Harvest",
    slug: "harvest",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["harvest","crop"]
  },
  {
    id: "increase",
    name: "Increase",
    slug: "increase",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["grow","more"]
  },
  {
    id: "overflow",
    name: "Overflow",
    slug: "overflow",
    group: "God's Promises & Blessings",
    icon: "undefined",
    keywords: ["flow","spill"]
  },
  {
    id: "cross",
    name: "Cross",
    slug: "cross",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["cross","jesus"]
  },
  {
    id: "crown",
    name: "Crown",
    slug: "crown",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["crown","king"]
  },
  {
    id: "dove",
    name: "Dove",
    slug: "dove",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["dove","bird"]
  },
  {
    id: "lamb",
    name: "Lamb",
    slug: "lamb",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["lamb","sheep"]
  },
  {
    id: "fish",
    name: "Fish",
    slug: "fish",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["fish","jesus"]
  },
  {
    id: "bread",
    name: "Bread",
    slug: "bread",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["bread","eat"]
  },
  {
    id: "cup",
    name: "Cup",
    slug: "cup",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["cup","drink"]
  },
  {
    id: "wine",
    name: "Wine",
    slug: "wine",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["wine","blood"]
  },
  {
    id: "olive-branch",
    name: "Olive Branch",
    slug: "olive-branch",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["olive","branch"]
  },
  {
    id: "olive-tree",
    name: "Olive Tree",
    slug: "olive-tree",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["tree","olive"]
  },
  {
    id: "vine",
    name: "Vine",
    slug: "vine",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["vine","grape"]
  },
  {
    id: "seed",
    name: "Seed",
    slug: "seed",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["seed","plant"]
  },
  {
    id: "wheat",
    name: "Wheat",
    slug: "wheat",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["wheat","grain"]
  },
  {
    id: "light",
    name: "Light",
    slug: "light",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["light","shine"]
  },
  {
    id: "lamp",
    name: "Lamp",
    slug: "lamp",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["lamp","light"]
  },
  {
    id: "candle",
    name: "Candle",
    slug: "candle",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["candle","fire"]
  },
  {
    id: "fire",
    name: "Fire",
    slug: "fire",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["fire","flame"]
  },
  {
    id: "water",
    name: "Water",
    slug: "water",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["water","drink"]
  },
  {
    id: "river",
    name: "River",
    slug: "river",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["river","stream"]
  },
  {
    id: "mountain",
    name: "Mountain",
    slug: "mountain",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["mountain","hill"]
  },
  {
    id: "desert",
    name: "Desert",
    slug: "desert",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["desert","sand"]
  },
  {
    id: "tent",
    name: "Tent",
    slug: "tent",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["tent","camp"]
  },
  {
    id: "temple",
    name: "Temple",
    slug: "temple",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["temple","build"]
  },
  {
    id: "ark",
    name: "Ark",
    slug: "ark",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["ark","boat"]
  },
  {
    id: "trumpet",
    name: "Trumpet",
    slug: "trumpet",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["trumpet","sound"]
  },
  {
    id: "staff",
    name: "Staff",
    slug: "staff",
    group: "Biblical Symbols",
    icon: "undefined",
    keywords: ["staff","rod"]
  },
  {
    id: "heaven",
    name: "Heaven",
    slug: "heaven",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["heaven","sky"]
  },
  {
    id: "eternal-life",
    name: "Eternal Life",
    slug: "eternal-life",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["eternal","forever"]
  },
  {
    id: "eternity",
    name: "Eternity",
    slug: "eternity",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["endless","time"]
  },
  {
    id: "angels",
    name: "Angels",
    slug: "angels",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["angel","wing"]
  },
  {
    id: "heavenly-kingdom",
    name: "Heavenly Kingdom",
    slug: "heavenly-kingdom",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["kingdom","heaven"]
  },
  {
    id: "new-jerusalem",
    name: "New Jerusalem",
    slug: "new-jerusalem",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["city","new"]
  },
  {
    id: "paradise",
    name: "Paradise",
    slug: "paradise",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["garden","paradise"]
  },
  {
    id: "eternal-hope",
    name: "Eternal Hope",
    slug: "eternal-hope",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["hope","eternal"]
  },
  {
    id: "heavenly-reward",
    name: "Heavenly Reward",
    slug: "heavenly-reward",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["reward","heaven"]
  },
  {
    id: "crown-of-life",
    name: "Crown of Life",
    slug: "crown-of-life",
    group: "Heaven & Eternal Life",
    icon: "undefined",
    keywords: ["crown","life"]
  }
];